name: Build on Linux

on:
  pull_request:
  workflow_dispatch:
    inputs:
      enable-qtcli-signing:
        description: "Enable qtcli signing (true/false)"
        default: "false"
        required: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # qtcli
      - name: Build qtcli
        id: build-qtcli
        uses: ./.github/actions/build-qtcli
        with:
          working-directory: ./qt-cli
          deploy-target: ./qt-core/res/qtcli

      - name: Sign qtcli
        uses: ./.github/actions/sign-qtcli
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.enable-qtcli-signing == 'true' }}
        with:
          build-artifact: ${{ steps.build-qtcli.outputs.artifact-name }}
          worker-token: ${{ secrets.PAT }}
          deploy-target: ./qt-core/res/qtcli

      # extensions
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
        # qt-lib should be built first as it is a dependency for other packages
      - run: npm run ci:qt-lib
      - run: npm run compile:qt-lib
      - run: npm run ci:all
      - run: npm run compile:all
      - run: npm run ci-lint:all
      - run: npm run package:all
      - name: Upload qt-cpp
        uses: actions/upload-artifact@v4
        with:
          name: qt-cpp-vsix
          path: qt-cpp/out/*.vsix
      - name: Upload qt-qml
        uses: actions/upload-artifact@v4
        with:
          name: qt-qml-vsix
          path: qt-qml/out/*.vsix
      - name: Upload qt-core
        uses: actions/upload-artifact@v4
        with:
          name: qt-core-vsix
          path: qt-core/out/*.vsix
      - name: Upload qt-ui
        uses: actions/upload-artifact@v4
        with:
          name: qt-ui-vsix
          path: qt-ui/out/*.vsix
